version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "discord.js"
        versions: ["^14.15.3"]
      - dependency-name: "mongoose"
        versions: ["^8.5.2"]
      - dependency-name: "noblox.js"
        versions: ["^5.0.1"]
      - dependency-name: "node-fetch"
        versions: ["^3.3.2"]
      - dependency-name: "whatwg-url"
        versions: ["^14.0.0"]
